name: Deploy Infrastructure & Backend

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Terraform & Docker Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      # Auto-approve para que no pida confirmaciÃ³n manual en el servidor
      run: terraform apply -auto-approve
      working-directory: ./terraform

    # CAPTURAR OUTPUTS DE TERRAFORM
    - name: Get ECR Repo URL
      id: tf-output
      run: |
        echo "ECR_URL=$(terraform output -raw ecr_repo_url)" >> $GITHUB_ENV
        echo "ALB_URL=$(terraform output -raw url_final_backend)" >> $GITHUB_ENV
      working-directory: ./terraform

    # CONSTRUIR Y SUBIR DOCKER
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        # Nota: El nombre del repo debe coincidir con el del main.tf
        ECR_REPOSITORY: dermatech/auth-service 
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Force ECS Update
      # Esto fuerza a ECS a descargar la nueva imagen que acabamos de subir
      run: |
        aws ecs update-service --cluster dermatech-cluster --service auth-service-svc --force-new-deployment
        
  
